<?php
declare(strict_types=1);

namespace Swissup\BreezeThemeEditor\Model\Formatter;

use Magento\Framework\Serialize\SerializerInterface;
use Swissup\BreezeThemeEditor\Model\Provider\ConfigProvider;
use Swissup\BreezeThemeEditor\Model\Utility\ColorPipeline;

/**
 * Formats theme config sections and fields for GraphQL response.
 *
 * Merges raw section/setting definitions with saved values,
 * resolves color formats, applies backward-compat guards for font palettes,
 * and auto-generates the synthetic `_font_palette` section.
 *
 * Owns FieldFormatter and FieldParamsFormatter as readonly properties
 * (no DI — instantiated directly).
 */
class SectionFormatter
{
    private readonly FieldFormatter $fieldFormatter;
    private readonly FieldParamsFormatter $fieldParamsFormatter;

    public function __construct(
        private readonly ConfigProvider $configProvider,
        private readonly ColorPipeline $colorPipeline,
        SerializerInterface $serializer
    ) {
        $this->fieldFormatter       = new FieldFormatter($serializer);
        $this->fieldParamsFormatter = new FieldParamsFormatter();
    }

    /**
     * Merge sections with saved values into GraphQL-ready field arrays.
     */
    public function mergeSectionsWithValues(array $sections, array $valuesMap, int $themeId): array
    {
        $defaults = $this->configProvider->getAllDefaults($themeId);

        // Collect CSS properties that are auto-generated from font_palettes.fonts[].
        // Used as a guard to silently skip legacy role entries still present in sections.
        $autoGeneratedProperties = $this->collectFontPaletteProperties($themeId);

        $result = [];
        $order  = 0;

        foreach ($sections as $section) {
            $fields = [];

            foreach (($section['settings'] ?? []) as $setting) {
                $type = strtolower($setting['type'] ?? '');

                // Skip font_picker role entries that are already auto-generated from
                // font_palettes.fonts[] — backward-compat guard for themes not yet updated.
                if (
                    $type === 'font_picker'
                    && !empty($setting['font_palette'])
                    && !empty($setting['property'])
                    && in_array($setting['property'], $autoGeneratedProperties, true)
                ) {
                    continue;
                }

                // UI-only types (heading, etc.) carry no value — include as minimal display fields
                if ($type === 'heading') {
                    $fields[] = [
                        'code'        => $setting['id'] ?? null,
                        'label'       => $setting['label'] ?? null,
                        'type'        => 'HEADING',
                        'description' => $setting['description'] ?? null,
                        'value'       => null,
                        'default'     => null,
                        'isModified'  => false,
                        'property'    => null,
                        'selector'    => null,
                        'required'    => false,
                        'validation'  => null,
                        'placeholder' => null,
                        'helpText'    => null,
                        'params'      => null,
                        'dependsOn'   => null,
                    ];
                    continue;
                }

                $key          = $section['id'] . '.' . $setting['id'];
                $currentValue = $valuesMap[$key] ?? null;
                $defaultValue = $defaults[$key] ?? ($setting['default'] ?? null);

                // Resolve format early for color fields (needed for value conversion)
                $colorFormat = null;
                if ($type === 'color') {
                    $colorFormat = $this->colorPipeline->resolveFormat(
                        $setting['format'] ?? null,
                        $setting['default'] ?? null
                    );
                }

                $field = [
                    'code'        => $setting['id'],
                    'label'       => $setting['label'],
                    'type'        => strtoupper($setting['type']),
                    'description' => $setting['description'] ?? null,
                    'value'       => $colorFormat !== null
                        ? $this->colorPipeline->format($currentValue, $colorFormat)
                        : $currentValue,
                    'default'     => $this->fieldFormatter->encodeValue($defaultValue),
                    'isModified'  => $currentValue !== null && $currentValue !== $defaultValue,
                    'property'    => $setting['property'] ?? null,
                    'selector'    => $setting['selector'] ?? null,
                    'required'    => $setting['required'] ?? false,
                    'validation'  => $this->fieldFormatter->formatValidation($setting),
                    'placeholder' => $setting['placeholder'] ?? null,
                    'helpText'    => $setting['help_text'] ?? null,
                    'params'      => $this->fieldParamsFormatter->formatParams($setting),
                    'dependsOn'   => $this->fieldFormatter->formatDependency($setting),
                ];

                // Add color-specific fields only when relevant (avoid null)
                if ($colorFormat !== null) {
                    if (isset($setting['palette'])) {
                        $field['palette'] = $setting['palette'];
                    }

                    // Use the already-resolved format
                    $field['format'] = $colorFormat;
                }

                // Add font_palette reference for font_picker fields
                if ($type === 'font_picker' && isset($setting['font_palette'])) {
                    $field['fontPalette'] = $setting['font_palette'];
                }

                $fields[] = $field;
            }

            $result[] = [
                'code'        => $section['id'],
                'label'       => $section['name'],
                'icon'        => $section['icon'] ?? null,
                'description' => $section['description'] ?? null,
                'fields'      => $fields,
                'order'       => $section['order'] ?? $order++,
            ];
        }

        return $result;
    }

    /**
     * Generate a synthetic _font_palette section from font_palettes[].fonts[].
     *
     * Mirrors how color palette roles are stored in the _palette section.
     * Returns null when no font palettes are defined (nothing to generate).
     */
    public function mergeFontPaletteRolesAsFields(array $fontPalettes, array $valuesMap): ?array
    {
        $fields = [];

        foreach ($fontPalettes as $palette) {
            foreach ($palette['fonts'] ?? [] as $role) {
                $property   = $role['property'] ?? '';
                $defaultVal = $role['default'] ?? null;
                $fieldCode  = ltrim($property, '-');         // "--primary-font" → "primary-font"
                $key        = '_font_palette.' . $fieldCode;
                $savedValue = $valuesMap[$key] ?? null;

                $fields[] = [
                    'code'        => $fieldCode,
                    'label'       => $role['label'] ?? null,
                    'type'        => 'FONT_PICKER',
                    'value'       => $savedValue,
                    'default'     => $defaultVal,
                    'isModified'  => $savedValue !== null && $savedValue !== $defaultVal,
                    'property'    => $property,
                    'fontPalette' => $palette['id'],
                    'description' => null,
                    'selector'    => null,
                    'required'    => false,
                    'validation'  => null,
                    'placeholder' => null,
                    'helpText'    => null,
                    'params'      => null,
                    'dependsOn'   => null,
                ];
            }
        }

        if (empty($fields)) {
            return null;
        }

        return [
            'code'   => '_font_palette',
            'label'  => '',
            'icon'   => null,
            'fields' => $fields,
            'order'  => -1,
        ];
    }

    /**
     * Collect CSS properties auto-generated from font_palettes.fonts[].
     * Used as a guard in mergeSectionsWithValues() to skip legacy role entries.
     */
    private function collectFontPaletteProperties(int $themeId): array
    {
        $config     = $this->configProvider->getConfigurationWithInheritance($themeId);
        $properties = [];
        foreach ($config['font_palettes'] ?? [] as $palette) {
            foreach ($palette['fonts'] ?? [] as $role) {
                if (!empty($role['property'])) {
                    $properties[] = $role['property'];
                }
            }
        }
        return $properties;
    }
}
