define([
    'jquery',
    'Swissup_BreezeThemeEditor/js/editor/utils/core/config-manager',
    'Swissup_BreezeThemeEditor/js/editor/utils/browser/storage-helper'
], function ($, ConfigManager, StorageHelper) {
    'use strict';

    /**
     * Lightweight GraphQL client for Admin Panel
     * 
     * Authentication:
     * - Uses Bearer token (Authorization header) instead of custom header
     * - Token stored in localStorage (bte.global.admin_token) for persistence
     * - Token generated by AdminTokenGenerator (via AdminToolbar)
     * - Magento validates token automatically via TokenUserContext
     */
    var GraphQLClient = {
        /**
         * Get GraphQL endpoint from ConfigManager
         *
         * @returns {String}
         */
        _getEndpoint: function() {
            var config = ConfigManager.get();
            return config && config.graphqlEndpoint ? config.graphqlEndpoint : '/graphql';
        },

        /**
         * Get Bearer token from StorageHelper (bte.global.admin_token) or config
         *
         * @returns {String|null}
         */
        _getToken: function() {
            // Try StorageHelper first (persisted between page loads)
            var token = StorageHelper.getGlobalItem('admin_token');
            if (token) {
                return token;
            }

            // Fallback to config (initial load)
            var config = ConfigManager.get();
            if (config && config.token) {
                // Store for future requests
                StorageHelper.setGlobalItem('admin_token', config.token);
                return config.token;
            }

            console.error('[BTE GraphQL] No Bearer token available - authentication will fail');
            return null;
        },

        /**
         * Execute GraphQL query/mutation
         *
         * @param {String} query - GraphQL query string
         * @param {Object} variables - Query variables
         * @param {String} operationName - Optional operation name
         * @returns {Promise}
         */
        execute: function(query, variables, operationName) {
            var payload = {
                query: query,
                variables: variables || {}
            };

            if (operationName) {
                payload.operationName = operationName;
            }

            // Use native XMLHttpRequest to avoid Magento's jQuery AJAX hooks
            var self = this;
            var deferred = $.Deferred();
            var xhr = new XMLHttpRequest();
            
            xhr.open('POST', this._getEndpoint(), true);
            
            // Set headers
            var headers = this._getHeaders();
            for (var key in headers) {
                if (headers.hasOwnProperty(key)) {
                    xhr.setRequestHeader(key, headers[key]);
                }
            }
            
            xhr.onload = function() {
                if (xhr.status >= 200 && xhr.status < 300) {
                    var response;
                    try {
                        response = JSON.parse(xhr.responseText);
                    } catch (e) {
                        // JSON parse failed — build error and reject
                        try {
                            self._handleError({
                                status: xhr.status,
                                statusText: 'JSON Parse Error',
                                responseText: xhr.responseText
                            });
                        } catch (err2) {
                            deferred.reject(err2);
                        }
                        return;
                    }
                    // JSON parsed OK — _handleSuccess may throw on GraphQL errors
                    try {
                        deferred.resolve(self._handleSuccess(response));
                    } catch (e) {
                        // e is the well-formed error from _handleSuccess (has .graphqlErrors, .extensions)
                        deferred.reject(e);
                    }
                } else {
                    try {
                        self._handleError({
                            status: xhr.status,
                            statusText: xhr.statusText,
                            responseText: xhr.responseText
                        });
                    } catch (e) {
                        deferred.reject(e);
                    }
                }
            };
            
            xhr.onerror = function() {
                try {
                    self._handleError({
                        status: 0,
                        statusText: 'Network Error',
                        responseText: ''
                    });
                } catch (e) {
                    deferred.reject(e);
                }
            };
            
            xhr.send(JSON.stringify(payload));
            
            return deferred.promise();
        },

        /**
         * Get request headers
         *
         * @returns {Object}
         */
        _getHeaders: function() {
            var headers = {
                'Content-Type': 'application/json',
                'X-Requested-With': 'XMLHttpRequest'
            };

            // Get config from ConfigManager
            var config = ConfigManager.get();

            if (config) {
                // Add store header
                if (config.storeCode) {
                    headers['Store'] = config.storeCode;
                }
            }

            // Add Bearer token (required for admin authentication)
            var token = this._getToken();
            if (token) {
                headers['Authorization'] = 'Bearer ' + token;
            } else {
                console.warn('[BTE GraphQL] No Bearer token available - request will likely fail');
            }

            return headers;
        },

        /**
         * Handle successful response
         *
         * @param {Object} response
         * @returns {Object}
         */
        _handleSuccess: function(response) {
            // GUARD: Check if response exists
            if (!response) {
                console.error('❌ GraphQL Response is null or undefined');
                var error = new Error('Empty response from server');
                error.graphqlErrors = [];
                error.extensions = null;
                throw error;
            }

            // Handle GraphQL errors in response
            if (response.errors && response.errors.length > 0) {
                console.error('GraphQL Errors:', response.errors);

                var firstError = response.errors[0];
                var errorMessage = firstError.message;

                // Create error object with full GraphQL error data
                var error = new Error('GraphQL Error: ' + errorMessage);
                error.graphqlErrors = response.errors;
                error.extensions = firstError.extensions || null;

                throw error;
            }

            // GUARD: Check if data exists when no errors
            if (!response.data) {
                console.warn('⚠️ GraphQL response has no data field:', response);
                return null;
            }

            return response.data;
        },

        /**
         * Handle AJAX error
         *
         * @param {Object} xhr - XHR object or error object with {status, statusText, responseText}
         * @param {String} status - Optional status (for jQuery compatibility)
         * @param {String} error - Optional error (for jQuery compatibility)
         */
        _handleError: function(xhr, status, error) {
            // Support both jQuery format (xhr, status, error) and custom format ({status, statusText, responseText})
            var statusCode = xhr.status || 0;
            var statusText = xhr.statusText || status || '';
            var responseText = xhr.responseText || '';
            
            console.error('GraphQL Request Failed:', {
                status: statusCode,
                statusText: statusText,
                error: error || statusText,
                response: responseText
            });

            // Check for 401 Unauthorized - invalid/expired token
            if (statusCode === 401) {
                console.warn('[BTE GraphQL] 401 Unauthorized - clearing invalid token from localStorage');
                StorageHelper.removeGlobalItem('admin_token');
                
                var authError = new Error('Authentication failed: Invalid or expired Bearer token. Please reload the page.');
                authError.extensions = { category: 'authentication' };
                authError.graphqlErrors = [];
                throw authError;
            }

            var message = 'Network error';
            var extensions = null;
            var graphqlErrors = [];

            // GUARD: Check if responseText exists and is not empty
            if (responseText) {
                try {
                    var response = JSON.parse(responseText);
                    
                    // GUARD: Check if response exists after parsing
                    if (response && response.errors && response.errors.length > 0) {
                        var firstError = response.errors[0];
                        message = firstError.message;
                        graphqlErrors = response.errors;

                        // Parse extensions with debugMessage
                        if (firstError.extensions) {
                            extensions = firstError.extensions;
                        }
                    }
                } catch (e) {
                    // JSON parse failed - use status/error as fallback
                    message = error || statusText || 'Network error';
                }
            } else {
                // No response body - likely network issue
                message = error || statusText || 'Network error';
            }

            // Create error object with extensions and graphqlErrors
            var errorObj = new Error(message);
            errorObj.extensions = extensions;
            errorObj.graphqlErrors = graphqlErrors;

            throw errorObj;
        }
    };

    return GraphQLClient;
});
