<?php
declare(strict_types=1);

namespace Swissup\BreezeThemeEditor\Model\Resolver\Query;

use Magento\Framework\Serialize\SerializerInterface;
use Swissup\BreezeThemeEditor\Model\Provider\ConfigProvider;
use Swissup\BreezeThemeEditor\Model\Config\PaletteProvider;
use Swissup\BreezeThemeEditor\Model\Config\FontPaletteProvider;
use Swissup\BreezeThemeEditor\Model\Utility\ColorPipeline;
use Swissup\BreezeThemeEditor\Model\Resolver\AbstractQueryResolver;

/**
 * Abstract base class for Config resolvers
 * Contains shared formatting logic to avoid code duplication
 * 
 * Extends AbstractQueryResolver to inherit ACL permission checking
 */
abstract class AbstractConfigResolver extends AbstractQueryResolver
{
    public function __construct(
        protected SerializerInterface $serializer,
        protected ConfigProvider $configProvider,
        protected PaletteProvider $paletteProvider,
        protected FontPaletteProvider $fontPaletteProvider,
        protected ColorPipeline $colorPipeline
    ) {}

    /**
     * Merge sections with values
     */
    protected function mergeSectionsWithValues(array $sections, array $valuesMap, int $themeId): array
    {
        $defaults = $this->configProvider->getAllDefaults($themeId);

        // Collect CSS properties that are auto-generated from font_palettes.fonts[].
        // Used as a guard to silently skip legacy role entries still present in sections.
        $autoGeneratedProperties = $this->collectFontPaletteProperties($themeId);

        $result = [];
        $order = 0;

        foreach ($sections as $section) {
            $fields = [];

            foreach (($section['settings'] ?? []) as $setting) {
                $type = strtolower($setting['type'] ?? '');

                // Skip font_picker role entries that are already auto-generated from
                // font_palettes.fonts[] — backward-compat guard for themes not yet updated.
                if (
                    $type === 'font_picker'
                    && !empty($setting['font_palette'])
                    && !empty($setting['property'])
                    && in_array($setting['property'], $autoGeneratedProperties, true)
                ) {
                    continue;
                }

                // UI-only types (heading, etc.) carry no value — include as minimal display fields
                if ($type === 'heading') {
                    $fields[] = [
                        'code' => $setting['id'] ?? null,
                        'label' => $setting['label'] ?? null,
                        'type' => 'HEADING',
                        'description' => $setting['description'] ?? null,
                        'value' => null,
                        'default' => null,
                        'isModified' => false,
                        'property' => null,
                        'selector' => null,
                        'required' => false,
                        'validation' => null,
                        'placeholder' => null,
                        'helpText' => null,
                        'params' => null,
                        'dependsOn' => null,
                    ];
                    continue;
                }

                $key = $section['id'] . '.' . $setting['id'];
                $currentValue = $valuesMap[$key] ?? null;
                $defaultValue = $defaults[$key] ?? ($setting['default'] ?? null);

                // Resolve format early for color fields (needed for value conversion)
                $colorFormat = null;
                if ($type === 'color') {
                    $colorFormat = $this->colorPipeline->resolveFormat(
                        $setting['format'] ?? null,
                        $setting['default'] ?? null
                    );
                }

                $field = [
                    'code' => $setting['id'],
                    'label' => $setting['label'],
                    'type' => strtoupper($setting['type']),
                    'description' => $setting['description'] ?? null,
                    'value' => $colorFormat !== null 
                        ? $this->colorPipeline->format($currentValue, $colorFormat)
                        : $currentValue,
                    'default' => $this->encodeValue($defaultValue),
                    'isModified' => $currentValue !== null && $currentValue !== $defaultValue,
                    'property' => $setting['property'] ?? null,
                    'selector' => $setting['selector'] ?? null,
                    'required' => $setting['required'] ?? false,
                    'validation' => $this->formatValidation($setting),
                    'placeholder' => $setting['placeholder'] ?? null,
                    'helpText' => $setting['help_text'] ?? null,
                    'params' => $this->formatParams($setting),
                    'dependsOn' => $this->formatDependency($setting)
                ];

                // Add color-specific fields only when relevant (avoid null)
                if ($colorFormat !== null) {
                    if (isset($setting['palette'])) {
                        $field['palette'] = $setting['palette'];
                    }
                    
                    // Use the already-resolved format
                    $field['format'] = $colorFormat;
                }

                // Add font_palette reference for font_picker fields
                if ($type === 'font_picker' && isset($setting['font_palette'])) {
                    $field['fontPalette'] = $setting['font_palette'];
                }

                $fields[] = $field;
            }

            $result[] = [
                'code' => $section['id'],
                'label' => $section['name'],
                'icon' => $section['icon'] ?? null,
                'description' => $section['description'] ?? null,
                'fields' => $fields,
                'order' => $section['order'] ?? $order++
            ];
        }

        return $result;
    }

    /**
     * Collect CSS properties auto-generated from font_palettes.fonts[].
     * Used as a guard in mergeSectionsWithValues() to skip legacy role entries.
     */
    private function collectFontPaletteProperties(int $themeId): array
    {
        $config = $this->configProvider->getConfigurationWithInheritance($themeId);
        $properties = [];
        foreach ($config['font_palettes'] ?? [] as $palette) {
            foreach ($palette['fonts'] ?? [] as $role) {
                if (!empty($role['property'])) {
                    $properties[] = $role['property'];
                }
            }
        }
        return $properties;
    }

    /**
     * Generate a synthetic _font_palette section from font_palettes[].fonts[].
     *
     * Mirrors how color palette roles are stored in the _palette section.
     * Returns null when no font palettes are defined (nothing to generate).
     */
    protected function mergeFontPaletteRolesAsFields(array $fontPalettes, array $valuesMap): ?array
    {
        $fields = [];

        foreach ($fontPalettes as $palette) {
            foreach ($palette['fonts'] ?? [] as $role) {
                $property   = $role['property'] ?? '';
                $defaultVal = $role['default'] ?? null;
                $fieldCode  = ltrim($property, '-');          // "--primary-font" → "primary-font"
                $key        = '_font_palette.' . $fieldCode;
                $savedValue = $valuesMap[$key] ?? null;

                $fields[] = [
                    'code'        => $fieldCode,
                    'label'       => $role['label'] ?? null,
                    'type'        => 'FONT_PICKER',
                    'value'       => $savedValue,
                    'default'     => $defaultVal,
                    'isModified'  => $savedValue !== null && $savedValue !== $defaultVal,
                    'property'    => $property,
                    'fontPalette' => $palette['id'],
                    'description' => null,
                    'selector'    => null,
                    'required'    => false,
                    'validation'  => null,
                    'placeholder' => null,
                    'helpText'    => null,
                    'params'      => null,
                    'dependsOn'   => null,
                ];
            }
        }

        if (empty($fields)) {
            return null;
        }

        return [
            'code'   => '_font_palette',
            'label'  => '',
            'icon'   => null,
            'fields' => $fields,
            'order'  => -1,
        ];
    }

    /**
     * Format validation rules
     */
    protected function formatValidation(array $setting): ?array
    {
        $validation = [];

        if (isset($setting['minLength'])) {
            $validation['minLength'] = $setting['minLength'];
        }
        if (isset($setting['maxLength'])) {
            $validation['maxLength'] = $setting['maxLength'];
        }
        if (isset($setting['min'])) {
            $validation['min'] = (float)$setting['min'];
        }
        if (isset($setting['max'])) {
            $validation['max'] = (float)$setting['max'];
        }
        if (isset($setting['pattern'])) {
            $validation['pattern'] = $setting['pattern'];
        }
        if (isset($setting['validationMessage'])) {
            $validation['message'] = $setting['validationMessage'];
        }

        return empty($validation) ? null : $validation;
    }

    /**
     * Format field parameters
     */
    protected function formatParams(array $setting): ?array
    {
        $type = strtolower($setting['type'] ?? '');

        $params = match (true) {
            in_array($type, ['range', 'number', 'spacing']) => $this->buildNumericParams($setting),
            in_array($type, ['select', 'icon_set_picker'])  => $this->buildSelectParams($setting),
            $type === 'font_picker'                         => $this->buildFontPickerParams($setting),
            $type === 'social_links'                        => $this->buildSocialLinksParams($setting),
            $type === 'image_upload'                        => $this->buildImageUploadParams($setting),
            $type === 'code'                                => $this->buildCodeParams($setting),
            default                                         => [],
        };

        if (empty($params)) {
            return null;
        }

        // _fieldType drives FieldParamsTypeResolver::resolveType() — not a GraphQL field
        $params['_fieldType'] = $type;

        return $params;
    }

    private function buildNumericParams(array $s): array
    {
        $p = [];
        if (isset($s['min']))  { $p['min']  = (float)$s['min']; }
        if (isset($s['max']))  { $p['max']  = (float)$s['max']; }
        if (isset($s['step'])) { $p['step'] = (float)$s['step']; }
        if (isset($s['unit'])) { $p['unit'] = $s['unit']; }
        return $p;
    }

    private function buildSelectParams(array $s): array
    {
        $p = [];
        if (isset($s['options']))  { $p['options']  = $this->formatOptions($s['options']); }
        if (isset($s['maxItems'])) { $p['maxItems'] = $s['maxItems']; }
        return $p;
    }

    private function buildFontPickerParams(array $s): array
    {
        $p = [];
        if (isset($s['options'])) {
            $p['options'] = $this->formatOptions($s['options']);
            $stylesheets = [];
            foreach ($s['options'] as $option) {
                if (!empty($option['url']) && str_starts_with($option['url'], 'http')) {
                    $stylesheets[] = ['value' => $option['value'], 'url' => $option['url']];
                }
            }
            if (!empty($stylesheets)) {
                $p['fontStylesheets'] = $stylesheets;
            }
        }
        if (isset($s['fontWeights'])) { $p['fontWeights'] = $s['fontWeights']; }
        return $p;
    }

    private function buildSocialLinksParams(array $s): array
    {
        $p = [];
        if (isset($s['platforms'])) { $p['platforms'] = $s['platforms']; }
        return $p;
    }

    private function buildImageUploadParams(array $s): array
    {
        $p = [];
        if (isset($s['sides'])) { $p['sides'] = $s['sides']; }
        if (isset($s['allowedExtensions'])) {
            $p['acceptTypes'] = implode(',', array_map(
                fn($ext) => '.' . ltrim($ext, '.'),
                $s['allowedExtensions']
            ));
        }
        if (isset($s['maxFileSize'])) { $p['maxSize'] = $s['maxFileSize']; }
        return $p;
    }

    private function buildCodeParams(array $s): array
    {
        $p = [];
        if (isset($s['language'])) { $p['language'] = $s['language']; }
        if (isset($s['fallback']))  { $p['fallback']  = $s['fallback']; }
        return $p;
    }

    /**
     * Format select/radio options
     */
    protected function formatOptions(array $options): array
    {
        $result = [];
        foreach ($options as $option) {
            $result[] = [
                'label' => $option['label'],
                'value' => $option['value'],
                'icon' => $option['icon'] ?? null,
                'preview' => $option['preview'] ?? null
            ];
        }
        return $result;
    }

    /**
     * Format field dependency
     */
    protected function formatDependency(array $setting): ?array
    {
        if (!isset($setting['dependsOn'])) {
            return null;
        }

        $dep = $setting['dependsOn'];

        return [
            'fieldCode' => $dep['field'],
            'value' => $dep['value'],
            'operator' => strtoupper($dep['operator'] ?? 'EQUALS')
        ];
    }

    /**
     * Format presets
     */
    protected function formatPresets(array $presets): array
    {
        $result = [];
        foreach ($presets as $preset) {
            $result[] = [
                'id' => $preset['id'],
                'name' => $preset['name'],
                'description' => $preset['description'] ?? null,
                'preview' => $preset['preview'] ?? null,
                'settings' => $this->formatPresetSettings($preset['settings'] ?? [])
            ];
        }
        return $result;
    }

    /**
     * Format preset settings
     */
    protected function formatPresetSettings(array $settings): array
    {
        $result = [];
        foreach ($settings as $key => $value) {
            if (strpos($key, '.') !== false) {
                [$sectionCode, $fieldCode] = explode('.', $key, 2);
                $result[] = [
                    'sectionCode' => $sectionCode,
                    'fieldCode' => $fieldCode,
                    'value' => is_string($value) ? $value : $this->serializer->serialize($value),
                    'isModified' => false,
                    'updatedAt' => null
                ];
            }
        }
        return $result;
    }

    /**
     * Encode value to string
     */
    protected function encodeValue($value): ?string
    {
        if ($value === null) {
            return null;
        }

        return is_string($value) ? $value : $this->serializer->serialize($value);
    }

    /**
     * Format palettes for GraphQL response
     *
     * @param int $themeId
     * @param array $valuesMap - Map of 'section.setting' => value (for usage count)
     * @return array
     */
    protected function formatPalettes(int $themeId, array $valuesMap = []): array
    {
        return $this->paletteProvider->getPalettes($themeId, $valuesMap);
    }

    /**
     * Format font palettes for GraphQL response
     *
     * @param int $themeId
     * @return array
     */
    protected function formatFontPalettes(int $themeId): array
    {
        return $this->fontPaletteProvider->getFontPalettes($themeId);
    }
}
